---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./controlplaneio.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./coredns.yaml
  - ./actions-runner-controller.yaml
  - ./fluent-bit.yaml
  - ./victoria-metrics.yaml
