apiVersion: v1
kind: Secret
metadata:
  name: miniflux-secret
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:1mPB/Qvniu3tRADlyEBYUOqg0vLyr7/jSqCOjQ6K4kt6PqN1Ula+0MC3EF2f9xcmQ0/QReKh0tkI6oNjAxFLiEX60rN99FRRVpmyYyL9PKmxHKFsExvvgzCYiqB5RCpV/xXrVw==,iv:T3x7XVQ2R954rJKtIeD7mwLVJpVobL9WPGc/yvZD1bg=,tag:kjcA82yzKY9Se/HC+ZymJA==,type:str]
  ADMIN_USERNAME: ENC[AES256_GCM,data:iwE+MrY=,iv:QgphFTu3RUxHcEEHhCe9lGDs4em2cTB38hQ4FcD8fB8=,tag:OCkc1S1Q860rb4npgQRZmA==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:rdHZdSt+u9E=,iv:APkeAI972S7T+ucLd9ySI8PXDvR9wdQ6hfiYaRJnPsI=,tag:8qu4kA8y/Qp2my/IaKFYhw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:K/BWTAEP8Gk=,iv:6z5ndieJzSi+nNEKLQZsFUBt+Z44ksd7kPJMPzppcXY=,tag:9JsR1S8O0mr+brwMjtd9FQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:cNe1Y23CSQcGbHX6mdiVsiKuwT3zRx0cyHxUixi1YQl0gIVvjo1aXn4=,iv:YmeNj3w+Slhf+Vqbtvxa0X8+lwa2a1Hg0Sq9VseSyvc=,tag:1ncOifyf/ysGFyGP6VKfiQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:K6I5F8DkZ6o=,iv:7oIamnv0i0kvg6XD5l3v3YcYhFAQBtUlZDr60Gle7fY=,tag:lH9m0k13gdZTkIrI7gsDtQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:J5JdM9hPg4I=,iv:aFtCLTFu3y23mKe2vrJb3zdVpFRPpRpp6GtELD/ng7A=,tag:ClrdGPA0ACj90ZTRXw5Bgw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:2SuXE8F8bdkM9u0sgZk=,iv:B8LDAvSxg0Lwr0CurpLQgWjSj3kRpByCUyCKCAl3N9k=,tag:4DMHUfJ9xMmLG5n/yaJOAQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYjdFM0V4bWl1RkJVemVz
        SU9zNWl6bzNvMm55SlJuVTR6YlB5MWRGenowCmxNWnZ6OFF4Nmg2bmsvaEpqWXdQ
        eFcyL1d2SGpIZnJMeVRhdTRPUDJLTVEKLS0tIENBVFVXclZiVjBmWEpMTGRqVkNZ
        cXJ6MmtXZ1I5NEFPSmV5amxJMXUrNVEKe/RWLH2mJHZhZeTnXxXiwtOMYU9cBqVt
        4uxQ1oP6Df8BiMlh4xXIS6/uyLAmm8+xITi0wJXb0MeQKMlqrJkSuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T16:51:26Z"
  mac: ENC[AES256_GCM,data:zS4df6GkuXOUIApgoq/3QALdi1f/abFQjZE3oFywOvRXkXtQYMx/eC0CClZriNNDR50MFUquxPVvNgBnBUkoq2Qb0MY0LY6zGM0t29Prnk+/JV52xuIEbSNTVl/okb3hAIYafH3yfhhJaSQogEOxbtU+nQEWlJhsliAApT1v1vE=,iv:ZIfm8wKKIKH8kiECRk2SJlOrPz/8+IwGMoA3Nr5lnu0=,tag:T4pNd9IFo/wt31ax+rgRaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
