---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./claim.yaml
  - ./secret.sops.yaml
components:
  - ../../../../flux/components/volsync
configMapGenerator:
  - name: pelican-caddyfile
    files:
      - Caddyfile=./config/Caddyfile
generatorOptions:
  disableNameSuffixHash: true
