apiVersion: v1
kind: Secret
metadata:
    name: pelican-secret
type: Opaque
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:takecLZKig==,iv:+O7XFsxdnzIQ4gWVSN9gIsDovXO9IzsmA+i/POuYjas=,tag:fYKFUmWxqi3dXI8yh5ERFQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:DXgPOLVgDELPkzhA0m7zuj/cats77hi6EvhmbHvt8dceioVWDin1ZT8=,iv:peFvAnSkOfCx5+TMJrS4h7pC/OUrgGoKvCPmKn3SrGc=,tag:udDsgw26rL4prFHCCFxgZw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZIvmjLmgDQ==,iv:s2/96cPjFJTIK9uI2WTP5nvakR9hEp4Cs18dUGNZnz8=,tag:zrPF93vyj2IgBNzDIU8NpQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:Vf3e4Dw=,iv:Ii/bszW3z9FG8L6vanM6Y1/GlMZ8FjsQR65zMt1NWnk=,tag:QEsZyMv+J/lU2tGRqGiovQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:C6CsHSo+0Q==,iv:SKdQP30M97y4P40lqW0MPMQG1GOasyRUg5IAgpTkRww=,tag:5I0JSFEarMUeEPopu7TvkQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:wTYHtxZKknEue84vq8Za8orTmY0FEmjK9MGf9o/8gBv364WxZWSkXMY=,iv:wTULOCsY0CeLSFplBLLS9/sS6Pvh2e1X0Uc/pXaqMCw=,tag:CVABcZh0qS5p9ttibAotQg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:OEuJJg==,iv:6JumOLvSjaRJ+eekhS61tzLmidU4TXORhgUKAN4Lqjg=,tag:e3GQi/7oEuASq2tNKhG23A==,type:str]
    DB_USER: ENC[AES256_GCM,data:j1wagG2mFQ==,iv:XReXBICDc/3IMYRKyJEdrTQw6b08bjeZbwKmAJs48kM=,tag:7m7PKo/86q3aQ15mHvyImA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:I7FhvGu43Zw=,iv:M/DrcQXC9rym230J9C51o4hZWSH5jA82KusN5ouNxF8=,tag:OZaIEl0Or347Od5peDJ+ew==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T11:46:09Z"
    mac: ENC[AES256_GCM,data:dfd0Hb5TegHUQsLICD2ypHdaPht1mB76TdMVyUSjKsrVCQeq0lC8x+xSwLC5h1SllsTrB3pJVtmJJdMwAeFNcFGsBAeZo+MKTtlGkG0Lp6oWdt9dBsm/8ct019VxNElCHQQdMusakJvnRxN+ds1yoUoqoXmxE0bSVM/alkATVTI=,iv:sFDcSkcvJEMIO6ejcO9GEL/XV4SWwKBT7aQ+A/u4vWc=,tag:6yt1fIX4Jkc3PiZcteBgRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
