apiVersion: v1
kind: Secret
metadata:
    name: pelican-secret
type: Opaque
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:takecLZKig==,iv:+O7XFsxdnzIQ4gWVSN9gIsDovXO9IzsmA+i/POuYjas=,tag:fYKFUmWxqi3dXI8yh5ERFQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:DXgPOLVgDELPkzhA0m7zuj/cats77hi6EvhmbHvt8dceioVWDin1ZT8=,iv:peFvAnSkOfCx5+TMJrS4h7pC/OUrgGoKvCPmKn3SrGc=,tag:udDsgw26rL4prFHCCFxgZw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZIvmjLmgDQ==,iv:s2/96cPjFJTIK9uI2WTP5nvakR9hEp4Cs18dUGNZnz8=,tag:zrPF93vyj2IgBNzDIU8NpQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FjLB9Oetixk=,iv:5kjpbHHbOGI/MANmO9zgYuGgDyrAbIt/CqWzC9QxwOw=,tag:tZV3it3MhwYYBYZdbnt3+A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:B/bMyHkFUWh8b7RMeW4=,iv:ZTiefQolaCAIHCpZWxJUo5EPP+HDW1/NRdRH60M43YM=,tag:+lreG8wKIhxzEblGDsDpMQ==,type:str]
    #ENC[AES256_GCM,data:VsfQPIFkfac4Qjc324hulGfJI9m+,iv:STLKTPF7MK6pqrqplNInmAKuFdTPUiQiCBpCG4YPUKc=,tag:bMyiCk4IuiAp5agYX8HvgA==,type:comment]
    #ENC[AES256_GCM,data:FIJX62KSxXfbtBrYafzFH6uITtXc,iv:cB3A6DCgo2YWQlrICMAxGLA6ilJ7iwJrxAEJiRTO2Jw=,tag:bqO7EO1Ap1oZZLLtw9duWw==,type:comment]
    #ENC[AES256_GCM,data:dhiHX3OonxiBxH9243m+Ywnuk1mVNhY4YEGr/AR/DZryk9X8M+swFD67h2pszO8UCa5O,iv:0WTvFuu29jOEGg1UfutNKNJQlI0rFUno/rhWm7MWogA=,tag:UVl1H9H+SjeDSOVYC7CLzQ==,type:comment]
    #ENC[AES256_GCM,data:Fl1lJ6SDtWgen+4N5Pgemw==,iv:QqoKLszioRkXv7ybLAJqnYb7vl4HlozXhPC+KBG3Hh0=,tag:Z383s4wAw80IZ3AKzaEpNA==,type:comment]
    #ENC[AES256_GCM,data:IEV5I6c4TRcZWI1Ea8aRpss=,iv:Bxb5IhR4nhxf610hB044U8Ex86xS4Y+PEoZGBA8E84M=,tag:IVMDeNAX45fsNZtTBR9rSQ==,type:comment]
    #ENC[AES256_GCM,data:9mxSaUc5li4vzQYaomiuNDVfGOi2Bg==,iv:emk4oy+EiqQHSJciiKb7ABIIKQCrmdfLZhlPEasgbPM=,tag:3L7lzf+iwAZj6kphi1TO4Q==,type:comment]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T11:49:22Z"
    mac: ENC[AES256_GCM,data:HI1q+Kw5sSE+LakYt/rVrGYQDUdtIs2a2xyTEYXM9QltLcuWgyHDHjPsso3s9wTrs4HfV1cA02mxA2ZRZJ1eWi6FeIHd2T4OzI/GUnsVrN8ZOfajydK6Dc6V5Me2xFF84Y/9R9FYt4DTnAQRgTsD52X093Wi3+WUMIH54038uN4=,iv:Y0sux3vhnQTD/PSdrInxiQO6pmFMxQd4ZjZP9CympGI=,tag:RFPaxGoqNbLd/Az3wy5t8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
