apiVersion: v1
kind: Secret
metadata:
  name: pelican-secret
type: Opaque
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:wDs1nlSuvg==,iv:3jFDbFWjN0AhuwtSdgW1XKIjAl6EiqjSu1krB5aV4pY=,tag:txjaRrsIiMJfXjFEi1dguw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:a6eqxmBRwb7z9j2do2/FrPL2VJR8fPX1YknShfgwHZWHlFTqA8MrV40=,iv:ggxo+m9r4oLftP8gp4Eg7H0fIVp6kyJUMByMa/ShLSo=,tag:HJvrwBgB2nQuqLtlsg2yqQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:T7e4IbOGfQ==,iv:tqP6k1s/WVop/lHFLWl8jy7iIPWeHP3y9MTyeNkZb9M=,tag:OIH8QFXCfF5pIL+w6TV87A==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FeQgLt1+jcI=,iv:/TIpewYwEH+xEPMPiOLbyejp0tMJ7e45Lg8f2Gz38FQ=,tag:hSU7NMc3QSKZyAOmqbPqWg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:P8ZR4MsCMaT8ZpU4eDo=,iv:cUinX9vUepYtSwUC4PL/nzd3lGBUgWZdHjHIuEJWRGY=,tag:SIreRYFEuWQ65rHMMNPh6A==,type:str]
  DB_CONNECTION: ENC[AES256_GCM,data:t4xovFA=,iv:svEjzR9fp+iroVPjtPBmS0sdqOCHYnkyUl1UpaDMoIo=,tag:OQiUlOu+MRC/qqQwmXH6vQ==,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:iZxakhQWjw==,iv:YFbNZ0s+mBBB+vR1igs+BUgZE8sXaAWv7pBb0YeX8VQ=,tag:Wx8UM6AhGpogiqCqDUS7sQ==,type:str]
  DB_HOST: ENC[AES256_GCM,data:BVKNfIXQY5JVRz7zE1MkJYLRqedJ/X3z90YcLMt9jjzjFmIS/HFUqCE=,iv:4ijeCwPHtmDIicTYmN/Px/Rww2cp93hJKZdIgx9tGJY=,tag:BhC4jHdSt0x+WNNybRXUMg==,type:str]
  DB_PORT: ENC[AES256_GCM,data:/66FYQ==,iv:ixRbXuMl9bQnDZblP95O2f9uHE7oj6b0Mb1EkPl0R5Q=,tag:jmjAWTxWSElVSOiCW45U9w==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:d0FcS6o0Zg==,iv:c6ANAXZZ6LDCtSMa3bkXstcjbN6UlTtkiJKxfRWU+yM=,tag:XCEabg7BMRgua7zBaKWHeQ==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:3HDFsQ3CcZY=,iv:LyyfmIQn+0csol1YVBBnSW8CT8HHaAU4ourL/ZlF/ec=,tag:tU8wvi7tvsVOa+0qtELYtQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UGFRbUdheXh1aDBqamZ0
        N3l1YWVkR2Jrei9yeUd6NW9vSUZDbTVVN1RvCjVRbVEra0V0cndHNVc5R3JETEFW
        dXI2VE43cnMxOUwwREZUd3hMQVVSLzQKLS0tIEN4NnBCWEMxa0dQQ3JLclgyTlVq
        RnhFNkxWc1Vmc2U4bjF1R3hOeXhjMG8K5xskbru8AjiRNV4EHtHzha30OToVsAiT
        H2vqMMLI4wPGbqVyPUkjHI5x1+aJupi4LwrU7KRDMVQ30jw6ieQ2jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T12:03:27Z"
  mac: ENC[AES256_GCM,data:W3Wlsn5XHM+ms0rgLQ9OfV+gSO19OsGyjhQ2BlfBYALWUlsxYSWbQb44YkjXVdy7gcW8cibvvDPiiDCmXFGUcUCwT6feYufscmfpb+CsZgKVHT2Rihkm+vyj5FHW13V+O0To8dOoamsFvQdyBNE0lMJwZ1R6ICtaZxJdZ8pEuzA=,iv:rjxSmn/krFdXPF9JaWi2IddFplN1f+X09WnjSEwQ1mU=,tag:IJVu0Xc8Dr1W73vdQ/AIDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
