apiVersion: v1
kind: Secret
metadata:
  name: autobrr-secret
type: Opaque
stringData:
  AUTOBRR__SESSION_SECRET: ENC[AES256_GCM,data:kawzlLfDoxwauNjm0sNJM2oLqzpvidW/WcU4hA==,iv:ufMBCNM9naT0bAiOWWuaKr8BxvxHC/Ve7U9bbHdtUhI=,tag:2m5Jm1G3LrR4+WC0h22Zrw==,type:str]
  AUTOBRR__POSTGRES_HOST: ENC[AES256_GCM,data:NBy8eJnJvZnYJLCiUW3ZybIUs89zEfs3Ii7NgygAfgvVOfg+IUy0x44=,iv:hMAEvX/hsmAhOUfjy1ng/R7405jlVl0HfGACQvMl2hM=,tag:kTb/Nc9XlDkMEX51d87kSA==,type:str]
  AUTOBRR__POSTGRES_PORT: ENC[AES256_GCM,data:bXGvlQ==,iv:Wd5E6+WrgXixgFNtDjAk6uiUg32hkZxEF9+pqQMa33w=,tag:CJHs/tg7CZ4sYwGnabjo4g==,type:str]
  AUTOBRR__POSTGRES_USER: ENC[AES256_GCM,data:a+KH83+Lmw==,iv:4Vp6vNTwNkgr9mTg8Yzm5SXKfawcqA0C8TSn/5EEnDo=,tag:5Un8q8471A2Y/dpQ3M43rA==,type:str]
  AUTOBRR__POSTGRES_PASS: ENC[AES256_GCM,data:3EWfVzb6gbA=,iv:tmQg0CEI8Hig79jcrj8ig3NHGEoOSZWkplC5FMLVCfg=,tag:uu6oef/5RdY1XNhPKbbfKg==,type:str]
  AUTOBRR__POSTGRES_DATABASE: ENC[AES256_GCM,data:uwfJrsA96w==,iv:DWE9w1cO1qio7iTpoL3Bp12ccQaKW3K1L1PtrWo3luQ=,tag:Jk49joEINepHbm9r/9NUNQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Fbe7TiUUMg==,iv:UsKPwdOJjMREAkYySIjlnNxfy1gdX+qWPq/W7j4Lg30=,tag:/l8tV3fUR4gtkGHbxlPY8A==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:PX+xqi0Foj2j1bwgZN2bl5ToqxBC1ggTSf3wuLb1yb8Ky5DF4TIWBqw=,iv:lPAQDjSa/PFfTO6n3LqYue26f0J6E+kpATtuNmx+44c=,tag:1j328gvgn7hABRJXsC5E8A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:6zCkxJ912A==,iv:ILTYENrK3OXeIcmFRUWxtrHNlHxZ6kKnxwwU8JLhREk=,tag:AVSe54gUIzBaJ8PVC5Nbuw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:IpU3P3v/Y+o=,iv:vnDlV/E1wMk9iYZxH23apjwNkO+HImnf3gTcS38aRJ0=,tag:7o49vxmD/5sKtFq9kpur+g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Sn1ZqTzTMHD/Myl8fy8=,iv:nv/J3bkh5J++vF9z0wQBVLXEv8Oz2yIBmldVbk31LRg=,tag:AMq7vWLlAHA+2fqSRcVSBw==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbVZxRFBRSFhqN0NndGNE
        RSt4UnpCVWJ3cnQ1UlFiZnZvU1U4aHUvRFNzClpkWFFCMTd2S0ZRUTBEb1FlVlc5
        UWdHQytxRUhLOHRwY0tyQWswU0lUM2sKLS0tIEFyYVd6MTF2VFFsT3F3M05ncG9a
        czdab0lZTlpubnptTnAvWURvWE1xanMKFgRi4VT5K/9iABYabzvHf3RLoCJiFN3m
        AgeQ29wcC/FMPLbEic5i+XovGY35R6l0LJH0DSMITfwVp/39kUp4zA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-21T11:32:51Z"
  mac: ENC[AES256_GCM,data:Esiv0YhlRuOzv5iSonPwXvrGkc9RZKxHzRq1ts9gwqNyaEPBaV2AevzSJg/u5xvnXHGwL7JtCAWeEVChiFT8ijEPT32Y1IYh8Rq3cepc+hkcFAJpgl+CcEJimTjMvVoP1+MpSTQB4WRDmty5C93BUbac+0JsqIVzuHNcBeyBreA=,iv:1vm4CcryBKHfvoeLtCD3w+3+dJ4M1dp0ts5pzID5uJs=,tag:OgTQ41oBhL4til5J2FOqKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
