apiVersion: v1
kind: Secret
metadata:
  name: claude-usage-tracker-secret
  namespace: observability
type: Opaque
stringData:
  SESSION_SECRET: ENC[AES256_GCM,data:3EJYMbUcJtYSD7pP95TgPQY0cuMV4Oepm7MvFBKT5xhqFo/al+H7ItMAX4I=,iv:P7/3FfllTwZtgjvWqT8Og8sR3PbD/n+7r3QXgT57hMc=,tag:YMwUFZ+7E/xW73rV0BOHLg==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:qf2ZLyM/RygWQ9+zjdUr9c9Q21rvc82F,iv:vwXb1MpPVTM6zT6ixLXsWHsIZ1vkDkVIjFc+IUKyiww=,tag:+8XQNG3HtxozDoaO9w7L5g==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ1BVSm1DWGZCdzMrZ3Zo
        OHVhTmRhc0kvenNRelRNOXVlUytxTUZLNUE0CnR3cDJjYU91OEhUck02R0pUOGN4
        cUFKaTFKZnhkQ0Y0bXJCVGlEZ09BQUUKLS0tIDVteTJrSmV4d2VmOVczUGhQZ0kx
        MXpVVkkyV2JIUXExTWd3Nm5lb1NBYzAKAcAUtiGNog347gZkybsPJhdYfykfJMbU
        QT4E7LwtI1P/qaek27e0SKX0ACcQb3yzVtT6AZRnMA3PnW4lt3N9Wg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T11:19:08Z"
  mac: ENC[AES256_GCM,data:tU0+Ax3oy3C3G5otvHjJwsLwIZT4nhKDTaI01UhgoorsoD7G684K2ClSHSNJR3heCG18Tsl6jY1AoQw6OPf+hH7XWbR3f7DAF92gTbl684m/iuezHK7rtmrJwJBKGysUvBpzngjf4RjGz/Q71hVUTU5yy40V7Q9gOXmBNhOWRYU=,iv:VzHOCLCzU0iKM9Xrk15PEGXOSyjiVf9k/1IBvh7WdeE=,tag:vews+0KuKdkBdRCXDgnEKA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
