apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
type: Opaque
stringData:
  DB_TYPE: ENC[AES256_GCM,data:pkxk1EgVN1OhPQ==,iv:VCVRrjTGq67i3t3AdtMjSWXaTRpE27H4QliYxllDbdc=,tag:4vsUDIX4ethOu/64pbft4Q==,type:str]
  DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:N/zTlhOMWQj/rrCvnR1UtvO0rZVTbXICtd4UoY2haF+DBrSmTl71U98=,iv:kcZSv9TaMpNsFPrImUA6o4JjmynbHsTY+HXs3Nl+/pQ=,tag:qQ2rZOsRWjWB9z/PDkk/TQ==,type:str]
  DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:o2EVzA==,iv:Kf+UQGKzkI14W/k6mHbaNmxifpwqu43/FXkMC0Ldk8I=,tag:LPUKewaadXX6O2DDWzsz9Q==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:Ny91,iv:VBBr0IYTrhMHP5+Y/xSXWGHqVEyDyHfd8PQ6HuVLpi8=,tag:fMDMIbQPOMsckIyBHWc5Fg==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:X/7P8+jk6iA=,iv:go1niijSwNi23ZLVwHaAGLTNBp7MBtfyGjfYHpjbDvE=,tag:Ss3jRa0kc5PWSnk9z++Jag==,type:str]
  DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:1fU1,iv:cDpMj0pTdbzyMeq1yQlnmNvb5gahSqNZEPpMm+uX6EE=,tag:AZSWvKw7Kl6IAmMouzLs0A==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:O+hp,iv:gxRztBACJKJnhFTqYNZ286mxiDfDzYo04syaSHcl4qY=,tag:27YIt9QKSGIjPfXgprfuGw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:eloUgXSi8a5rexqqJZd2ds/Ddr1FW2LtKT5/ae6tEYUsBHPAkno55S0=,iv:0+qNzmi6tXsFBpn24RvKUs1q4i9IdIU746vA/hmkqLU=,tag:pbVYEJLEQ39OyMB3+HVCBQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Boa1,iv:H4YmFcW8fYtqZayBVq2ItkJLSLzOJ+2rHcgY/R+bD3E=,tag:Id4GPAX6MhaVZSuvXY8QZA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Uvte9zMNi/M=,iv:lytU8MlxO1/gUzdDi2cn3Ts+CVVqNZJvUe4tozYXMUM=,tag:GmtMU2/l1d4MQ3Q6yVbXcg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:edvwY+NAulC/YlvTE0A=,iv:UaSHCRdC9MQGeUdq5/8p0QitGWR5Xpsxi4HOEDehBWM=,tag:f88x1emrRn6hM8sGi7Z6fQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcVQ3TEYxY05BaG1KNVJk
        ak9DcUkzRFArbGpsR2Q2QXNYc21RTC85ZUh3ClU0b0FsVGEvWlJWZXdDY0xHa0hM
        M28vSnhUVHcxV21XU1cxOGVXTzZQZ1UKLS0tIGZESTNMSi9XcjAzbXBOY0Z1dlc4
        Y0dUb09rZTRJakMvZTdHT2FJWWxJTnMK+l8e4TpoJOcZAHc6eNYN1IeajOBisoBs
        +zygP82W9LTnIHIsvTlR5Hg6PixSjukEI2+yEHbL2gIxRmagwIGLPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T11:39:00Z"
  mac: ENC[AES256_GCM,data:zBPTlebH8j/JOZxLdwn9vTOIGWPyR8PkEWsRFfuVEOggyA4U8Hhb/ILS9XzpGCJO2c2R66TiCU4/sXgQp4GY0/otSpnLM5fAyXmUdBGhvvdp+gkEQPDGnSNHr3aEuwrVaEytE8pYblPxvyE33PgLSrRUQECkALyA0EfFFY6FYsc=,iv:FN9xhzgb6dDC9p6uyXpWENItJGWjBxDZUI13UxRuX+E=,tag:EG43qGUP4qbEum/IDUeBHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
