apiVersion: v1
kind: Secret
metadata:
  name: volsync-secret
type: Opaque
stringData:
  VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:HS7Mci79iGdqTEt7POsk,iv:sCOdPebWXt6RhgVp3NI9xa+Ei1MP1qq4SSmkiHIQMbE=,tag:NvGZgePgrlncdIAkaCLrLA==,type:str]
  VOLSYNC_S3_ACCESS_KEY: ENC[AES256_GCM,data:4surmw8=,iv:m3R6AsWKuGmi38jKL1+JIN8KmdrzH3d53TJkiSy4StU=,tag:NHanB1WkZcdFcOG+9rPlsQ==,type:str]
  VOLSYNC_S3_SECRET_KEY: ENC[AES256_GCM,data:bq0DXdCxTJSH6NSHdqE=,iv:QIK84XL3rY4gtOrK9K0k5RGQoFR1FpofhrRPnXANiFE=,tag:XDQDY13DMcvmioBLVSZqMw==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VlpPV0tsd0Nwc2hKa21w
        eTBDeEptODNRcFl6anl5TlJUcWdJRXgrMmtBCjZFMjBzK05NKzhqUHNmenVWR0pt
        ZS9HZlQ1M3VxMU5maFo3dHpTdURBd0kKLS0tIHA4R2doZlBBSXpXTlZFOW5Sd25v
        V0NtU0R5c3NDWWh1MHdOQUFPaTZKWmMKp6RJ/BSPzHIB4zmlTTBVu78ObWf6l2ad
        XrTm0dFxUv0CHhERY/v6fTWYC7NVwF6eyaQkHDwQjX2Otg/MyVDDVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T10:50:28Z"
  mac: ENC[AES256_GCM,data:Nkh7zhRTzYly1S96fB9fth4DYnqan3NUTju5Sq6hegegHZq97mOqX24zPat4d5kG94WJFSMQWKj0FSm0pRpRFX8E2WlIWwGhKQNxKwjmGMjckS5OgpUrWCoeA95kJybFpsWA1T5KL8I2ST5sVTiKjpue60v1Z9SSHBrVh26A+jo=,iv:RWxwXNJ5tWpOAv1KFNc7Sbseja2JopSzqpH9EMvSeFU=,tag:7GCaFUE1NC9AXGLBopyMsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
