apiVersion: v1
kind: Secret
metadata:
  name: readarr-secret
type: Opaque
stringData:
  READARR__AUTH__APIKEY: ENC[AES256_GCM,data:wjuz9bN4FKVKJuIV6HjGRa7sYerhAnoGfWqP8nThjs8=,iv:W422ECBaKZvbENvTp6c6w9o4U+4Sv7xi+KfTqZXISDQ=,tag:rQ3GPoiV4Ep2KsgzVjYw0g==,type:str]
  READARR__POSTGRES__HOST: ENC[AES256_GCM,data:CmgIP79ohEOzxDEi1BHzYFA8IfcDx/o66RlYGhwS352cF6QtF/Ysh3c=,iv:T5NrH6z9S0IuPpz0C2NRkBob5STcT3kbZwLafJXvH+w=,tag:Ur89vRSMmp5ZUCVI6k+4qQ==,type:str]
  READARR__POSTGRES__PORT: ENC[AES256_GCM,data:FL8Zfw==,iv:w9PIAfDeZPdmPjXgU2SelRLFzpxQofkezec6s7NXO8Y=,tag:v9UI4fYOfzzv8EJ/sC681g==,type:str]
  READARR__POSTGRES__USER: ENC[AES256_GCM,data:IIvk3eDhlg==,iv:RGpveA0UDmJw/5Wa1dBfbacFuQPXvTVJiYJL4BX3maA=,tag:PVzliw6v/wi3xMy7a685cw==,type:str]
  READARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:WEVj0K5pgK8=,iv:Baqst72kf7bKBHnhQ2WpXBA2+n3OhPUMjTg7k7XdQDM=,tag:3fau3deV0JzuFMjUhoRzPg==,type:str]
  READARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:GYDsv5DHYagOE373,iv:+Q8awROAkUfqWMneI/PtxxscpV/Wxx0HIPfRLWK5Uw0=,tag:JM8/MleEwq/Zs/y0l7Ymyg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:FdrdEmlC17lqE1dD,iv:BazhOJIVYPmaJFEN9x3g9ErCVhW8hmCaJNBmYmDAqfE=,tag:2t0TXbKJ67oqxoyxjhuQtg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:fEEVNN05Y+p8URlkgutupuJ/rS5sN4k2VcSW9pc9Gse2NrpPZKFfWjw=,iv:EzqRVYVGq8Jy0m+jshlJslBqFgzhNwI6rmmMc/aQ4Jk=,tag:a9bFzhqfFElAn6rjimsGuQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:UOfa4bSZXw==,iv:+VlkW8bvWJHMWffUa575p/5flz1wkid8VHHHLK3WlKs=,tag:Z85KOmcLIJn6kEE5focJTw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:JeEfTalOxjg=,iv:stF93cek8MWyZvAgCxDg3qPoGxvpOxvUpiLkq3rssao=,tag:Z7qsDSLORbcYUgHWd/eztA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:o2o3d8dRPr2zs6B/rC0=,iv:n5GoWk5hFzBKwPzb3H8zoOvvdEJJTNqUYe2cwiBl8OA=,tag:AA0ibduA7mKJMsRgjW60Vw==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TktZS1hNcTZjQSs3YWt2
        NDlHWDBFNjR1MWpGd2VwZjVMZXJ5bEdIUFJzCk9KRE5LSWxvZFlheURRdjhaYTZV
        SmlzSFBBUnMyVDl2ZkVnMHlCOXhOV00KLS0tIDF6S3l4SXUycEZHVFFyWUgydzlZ
        aVhwbGUvZGcrbVV4eVd5VTl1ZnR1Y0UKAGPfrcOCwal6ufKPUCX9n4GBeiuAshs5
        PyD5Jo3C+iHGikExU2K0/wYS9UQHfB4Y9/oCoPu/HDHtRJr/n9NTuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T11:38:59Z"
  mac: ENC[AES256_GCM,data:3010KWZgx70w/L6MGTTjKCJgzd0hYuOsGiJhIS0WBZoGqEn4vPW1uvw/f7Tn8sitL+QdhvXWPYYqObUGtCPi1XzI5t6YUl0hNyYkJP88srGKfsytTlCcs09pxlmuFKTaDc8WXexFO6mgokF2vioTnK5w1d9Z24aznTEZxgYz6nQ=,iv:Wm9VvYZ7/3osQFBHQfyiJpXa77+gNyBNBMv0/AJvFrU=,tag:idHbi0Xlq8Y/lvIz8pWheg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
