---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

metrics: true

storage:
  type: sqlite
  caching: true
  path: /data/gatus.db

ui:
  title: Status | David Home
  header: Status
  logo: https://avatars.githubusercontent.com/u/47594764
  link: https://github.com/DavidIlie
  buttons:
    - name: GitHub
      link: https://github.com/DavidIlie/home-cluster
    - name: Homepage
      link: https://hp.davidhome.ro

web:
  port: 8080
