apiVersion: v1
kind: Secret
metadata:
  name: paperless-ai-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:ZBTHVaj39oFIe/PEBKbB3w2FsM0Owj56Xr39/+e30X+Asm9UYsmkrg/JawM2HUIJ+77D2PcLJkc8GwAS35yBIJQ5lE0=,iv:rlRrlQ//N79vxRNOIXNRPU+WooxaFilJRE1N6DReF1A=,tag:1vgIYwLdXG1QMED/TJyzuw==,type:comment]
  PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:0sxGYygUqYVvWDxTETEfHGhajOLjN6Rr0gNYuzKJAeHgZ197tAbZEw==,iv:2BfW7FFbQ77Px5mMBslkqf5+68YAdcZJUfB7iH3+0eY=,tag:cKfFWgrDjPIQDVM8JSujmQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOGo3TDg5bExpZVJTZUVv
        WitiMWdMWlluUTNpVHV3UHNNNTRlTHNWZVRFClJvczRkdWVrcm1neCtWbkpGYTd5
        bS96YS9EV2orQ2NxanloMmE4Zit5ZzAKLS0tIFFwNzFSV0k2TUh5VitQckFZNXp2
        L0FEMFlRbUdMRTlyRVlzQnd5eWJFeTAK/8SpwpOPjj/U3Od4z3WImtMlG19kMw3N
        t7d3tS1V2OV6Chhh5NB5GhuKY+1/W+u0Tl1fJ7lbbZ3kvTtvbOr4+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T00:00:45Z"
  mac: ENC[AES256_GCM,data:njv5gUedN9gVy2Tfje6w+w8IDCAiRUyqr4YMuAE272tJO9yob1iYdDxecZqLdoJtR5ZmZo6wRR6SxgVbxaj4LMXmrr+t/ZVR/fqwSmvzGdWTIemD0L+BAtHfLPT3FNk9RXxYWjOyde0vY6TpIXJs05sgLUN+NaiT9fiiKjWDwv0=,iv:2+HLeQqJJM0OoP2Zp4tUHhiAxtHxeYkeRBW7+qbb6Fc=,tag:81WdBG1mgUJtWZesrDEQ0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
