---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: uber-item-viewer
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: uber-item-viewer
  filterTags:
    pattern: "^.+-[a-f0-9]+-(?P<ts>[0-9]+)"
    extract: "$ts"
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: uber-item-viewer
  namespace: flux-system
spec:
  image: ghcr.io/davidilie/uber-item-viewer
  interval: 1m0s
