apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:ZnYkfEMyyLZuYLSoTWGLbCbZeNEHf1UO4gHpay7dSAytWIeGo69pPFOnYiSBmce0fSB9Y1J2dzC++4yEkFxOCA==,iv:AWTDsknx3o/aM4+kZFqFC2OzuOanZZcYFy8PIu3SoTo=,tag:+u7ZxOnr8gnMORuNcaP1og==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T22:56:16Z"
    mac: ENC[AES256_GCM,data:/X/H0yFBSiCzdM5vtKg7f/QBUs0EjJrQXTv2Ae8P30NKdrLM1JvEi1Ct/UkPYYkZ2Ic8a19yWrs/TgGD5Fdi8mtCNJm7Od/bqS2O0dil56Rv1it3xZdSiKbcnnHk0XfAvtCGCe6qEm4uVDgkSjqR4UMQ7BsVccZsFzazBgBmW2M=,iv:/m1LQaQkVtM0ufhDxdK8S1Yd+RxxBoJK7R4XXMSqunk=,tag:Imjv0cM2N3ntq9iTmYvZkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
