apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
type: Opaque
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:SAy6nbez6ZEBPsBaVHiC5aqscvut0UlHrmPSxbYNvEzGx/D1OFQC4Lsw0bQ=,iv:0OejfP3596y1HxbffKpFqHzjiof1ElqVQxq60VisPmw=,tag:lD+RgT8W7I5KT2DSDn9mJQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
        amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
        ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
        MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
        g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T23:00:43Z"
  mac: ENC[AES256_GCM,data:9QBhUBojd2+v+x/F4K35nL9kjN9C13api2lsuZfpOAmW2Ysms38ir+yA/eU3iDwG4KilnseXoOwNC7m+iXnCdQVK9yVhgUtacfcnIifa0GeXPeyXVH0YvsFuKPLVuucPdASLFY50j2x2hbHg66zwLzbZ1iXayR76QmEF/RdhzwU=,iv:PzsBPmXMgMfWjjCAxZ+5/XQevshTGfidCC6/xr5ipZs=,tag:8l4nqOgs9aNAr/Y6j/nZWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
