apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:5auwbC7LkaWbHA==,iv:tMaZjdbQxZarLsPrgaT9M3/6DUrXj207fQUF7149sSY=,tag:MzhcdDe3U7m/6lG6hBwixg==,type:comment]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:Jk+S+37sm7O7+4kgsLdNAF2hGXtWqBrqSijVKqrbNBgUkaM9ifzyFSNwGwhBoN/qE9ApQRcNw9YKkvzMS8JiPg==,iv:nTUYNWzoPZIlw+If4bJzFnqU8enHcC/JoZ4dUxoinpk=,tag:JdE+rhUpqym5XfetAY67tA==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:AoEznUw=,iv:nRQ6yWEQUk2LtSKWZ/AST9ArntdNQMm3B8AOlb/QLfU=,tag:RWE7BP9zpTcsbCd8bG60dA==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:kNwlBYlFofw=,iv:YFMsxcHrUZI5zUPaBtQYUcrGlXqnDS/lI4d8yyr6GNo=,tag:nk/FgTYDiJbpSyz3DXxcpw==,type:str]
  #ENC[AES256_GCM,data:OWbUdT5AwucI,iv:ZHIl4OMyAbrO+bn6ujjWDGR+f/wjwLfeMA/jxqSHT38=,tag:XFPA7EQHvrBmm2gQx9/M+g==,type:comment]
  PAPERLESS_DBHOST: ENC[AES256_GCM,data:S1Qu1Lkm/gwq8IdZw0q75RSVXvvg4tzp/bEm7joCc1+NCLPmVvXYoMw=,iv:zP6eAvniQp5AP6CGNpUq0dNE4qZ2/P2s1xocTDi0dxE=,tag:0GQXSDgdzsZZ0BflANmZNA==,type:str]
  PAPERLESS_DBPORT: ENC[AES256_GCM,data:w4EElA==,iv:qRxXpzZnsAJl/XT/sfC3D9h/2r9QRUzvzUvcCrYgl5A=,tag:sK2ghEf83QnX76RYU7ccfA==,type:str]
  PAPERLESS_DBNAME: ENC[AES256_GCM,data:22VMXsvP0rqE,iv:TC9VnuESYMKg/7wsgqFrhqpS280sF4/neYbz0AFgqtc=,tag:oi5MpNEzUb/8i5TCUFpjtw==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:bzqnXKc5BQtf,iv:SBpSHNFyjrP+u7/2QED1MK+MSoAPlwUswkfGYcOpemA=,tag:6qY0abTmLtQOJ3Asoy+c7A==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:Ohy83jaei9c=,iv:s7MA5DyhBUJjuoUGX7hcY7Jieseu3T7ixNaCRrcXhXA=,tag:RNjV74fmZwTVBiivwr7LVQ==,type:str]
  #ENC[AES256_GCM,data:0S1J/bl35RvWFVHpqa0=,iv:3CtZx+2tYIjk2E2U9Kyg+xmzfO0XrgeA2he5Wi10uJ4=,tag:CB779rno+Ecv3GMPjE+maA==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:aavSO+Ptu+f4,iv:p8VXXfeS8ads5IdfGXN57+/Yz0VFkd+yIxMNTILJdYA=,tag:uk5CJW9YilkD209GkGJkYA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Y5+UBY8T5LNvt8XpCAf4Ev3Fryht6wmJEWKeW7vpSgycn3Zj2cGzuJc=,iv:GXs22PrCDU5sdkc6MIX9s0GSNJzAiX45CVuTzk3rhV8=,tag:SBgRy5Mgej044D0ui0uzLA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:JBv9f/8Ab76d,iv:0F8RRDmgUAx4X7z/kZIdybinC+DvORClUBaD+J/ehDo=,tag:FtiGPG58tpwDhnZBgChvCQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:VUocfFZRVII=,iv:31eH8+WczFEy1oPSkpHT+X4MvXt+2PRztwfdJwQ5kKU=,tag:M/jRqz4IY8pdXuPf1PHypg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:4FXewzH+RR1uCQ6jcIE=,iv:TWeE/IVp5L+ONcvoYo2yvHt8/uUMERoxS3Ijnyqaj3M=,tag:sV8666Qsq+t1IVaV+HrltA==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUTYwWmh6bnhXMnpYb2FZ
        N1RqTUNGdmMxSjVTdWlOUmNJaHBOdVU1ZEI0CjNOay9PQmRBeG5FM1Q4QTlQMXVO
        aEtkYmE0VUg3bGFkYUV6bXpQWUYybGMKLS0tIGlwZkROK0pCd2ErYmxGTDBBU214
        VnVwTGZOQklKaXRiR3ZzdW1SNEs2WEkK/w3aoJJ7LTbipqHGVIIo7DGvpdwAem6j
        3d1R6N5iYKqqPQhGvgvoYmFEpJ6MSzdKEfbU0Ko4VS/Vxc9c3HDYLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T16:52:14Z"
  mac: ENC[AES256_GCM,data:6AKv8vf1qAcHIA5/8W3zsgcCLPuT+1T1Va/1GScCdjaqdNZLiQHUEQ+JQ07k00NUkj+p7ZNAVdAcgILjjp4vVlnYVh+DfI0DZVcjXnsjT179SB0A5ZdI0MF590GgMxlWbPfZAVEUUCXpI/H2tqIm/QSHBt83J74i5ieCiIJie+c=,iv:objSjA9eNia7wbA7/Tw6Dul6TpBRIkzZMUU6yrZMwxo=,tag:YHEOUfvjO7FoSS9n5ItgiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
