---
apiVersion: v1
kind: Service
metadata:
  name: &app pelican
  namespace: external-services
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ports:
    - name: http
      protocol: TCP
      port: &port 8080
      targetPort: *port
    - name: uberapi
      protocol: TCP
      port: &uberapi 4567
      targetPort: *uberapi
    - name: dynmap
      protocol: TCP
      port: &dynmap 8123
      targetPort: *dynmap
    - name: anadynmap
      protocol: TCP
      port: &anadynmap 8133
      targetPort: *anadynmap
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: pelican
  namespace: external-services
  labels:
    kubernetes.io/service-name: pelican
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 8080
  - name: uberapi
    protocol: TCP
    port: &uberapi 4567
    targetPort: *uberapi
  - name: dynmap
    protocol: TCP
    port: &dynmap 8123
    targetPort: *dynmap
  - name: anadynmap
    protocol: TCP
    port: &anadynmap 8133
    targetPort: *anadynmap
endpoints:
  - addresses:
      - "192.168.100.163"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pelican
  namespace: external-services
  annotations:
    external-dns.alpha.kubernetes.io/target: external.davidhome.ro
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Gaming
    gethomepage.dev/name: Pelican Wings
    gethomepage.dev/icon: pterodactyl.png
    gethomepage.dev/description: Game Server Node
spec:
  ingressClassName: external
  rules:
    - host: &host pelican.davidhome.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pelican
                port:
                  number: 8080
    - host: &uberapi uberapi.davidhome.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pelican
                port:
                  number: 4567
    - host: &map map.gurt.ing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pelican
                port:
                  number: 8123
    - host: &anamap map.anaxax.tv
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pelican
                port:
                  number: 8133
  tls:
    - hosts: [*host, *uberapi, *map, *anamap]
