---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: &name kopia-repository
spec:
  storageClassName: *name
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.25.3"
    path: /mnt/data/share/client_user/kubernetes/kopia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name kopia-repository
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: *name
  resources:
    requests:
      storage: 1Mi
