apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:3mKPMmgQEeMRQO+lVA==,iv:l7qXGTENccteR3Tg5gyNZWOTg9opJ1DXtuw4oETc9II=,tag:x+K1OQB21eLlO6DsA+dOWg==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEemlNWWYvWHpqOHhQbExW
        Rlh6dlZVc25DQlVrMlowbUZQSHdNaUdoUldrCjhyeE9BSi9OZ3RVa29JbUFjN3BM
        MXhtQXUxcWprMUVSdXRRMnU1L0FQQzQKLS0tIEt1dWZ0ZUpCOXIvV1RqQnVxVHJo
        QlZreFRoUjdpNlp4U2p4Q0YzQUYwMHcKeJSHM6ojCIzh0a83ABfj6nRcDsowr/L5
        RXZGKHkCNzJRwzfe2TSm+r0u65+jPqqbqGa2jx9OgvyH5WNVOWCeLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T16:54:01Z"
  mac: ENC[AES256_GCM,data:TTDkiRQInjThdKxi4wBT3nUBQdSmtckb5BLOru9gQVuBdtw+BDRHyYT9Vu5ALrqBCoFXZVKbBx5rVofu/x/55Hu/Cm1oWAQTv3lqrLN6Nad58KuH6ddSy6adnE87HOb+jF5T68LhImz/MV2Tctg8PJ3A7KKJwy3HVJeHV5qfeUQ=,iv:TIj9p2jMwM60xgzwk1C8AZ1OUpAGTU4SpRnwMvQcBSA=,tag:Dp0Ksen3w7CqDSgWD638yw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
