apiVersion: v1
kind: Secret
metadata:
    name: plausible-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:gSztCA8f9fXi26ElKn7gmVLa3Oi4Nz6//UUj4ebHc7YlD/VNZe0df04zeJRQw94x9l9WKHHuyJrmhvbct/+IYW51lNPbBqZBMvsyE3ThhuQMnRfjrKJ3o7CG1Q==,iv:VX0yilAhAtgt6+ao9N9yj2V5ipXCSSMn0i0NKABSNco=,tag:TpPgLzzJ6EpI4C4w04vu4A==,type:str]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:mhC5bdkzZS5PM40SeUkRDhNcVAmr+Pypejfu47ZxmHmhmk+/zYM4yw==,iv:sDGyWQlk8BASOXsPumrpSeMu/JYvP+Oc75HNjuxAFsU=,tag:9433CFqbXeUo6A1zvsnwsQ==,type:str]
    GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:XFQpafhp,iv:TyswsBySpbU/g7u2vHb3TYg8BvrY0y+ZWiS78Dz/A9U=,tag:Y73rt5NUPW8dlcN/m+0TaQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:jB0m7Ev1TtgHpB1eJsS0qQyNrkDRHtaQVzfvwCTPPzeuP5AWxOPrtauUwtbeQXHjjj0I/AC2IhVIfb/yLkqp/g==,iv:0/BTBE5ba8kBpVBuUYCMKeTNa9UTtBCB+MHMg9CxC3I=,tag:A0hTD4E3ft3vT9cDA3+KhA==,type:str]
    TOTP_VAULT_KEY: ENC[AES256_GCM,data:8Ekq/bIOFYOy/yIsM0e5urbVdz/xFwn0LosJpGBy9/gqvRj/WHc8LSa7OAQ=,iv:0mjyCXTm1SRSXRDY2jwH7NfD3N6l6HocUSl1hTjmQNY=,tag:oYXvr1r3yEM1C8g5yRYwgQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:Hsxchr+7T2RQzpXSs/JwOas5gyBYR4eL/D4fKCoB6lHoM+I5xWn+MemNMOK1M53e8TnyNl4nDKR653R+VGScTF3wuUVklP0=,iv:0Ok+DS0+xoCrNAGH6f3/MY+jMKQK2pg2PZk6XN0RMYk=,tag:UdKmY3frsCuyU8WH1Bz0eA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:gJv/9qttD6H6SjsHzUvKRl5/HyS6fl/xP69JgunWUWOez7g=,iv:LA3E9KmZqMrfnsp1WDDFAnAnKOXAwUMkXuaWDFctmvw=,tag:FZGUV//516ESr/k7dIjuCg==,type:str]
    MAILER_ADAPTER: ENC[AES256_GCM,data:TsNL3ZG7LABaoA==,iv:i2M29PnGYuqhToE5CyTG0Z9BRcAEQrGP7vpPEY4880o=,tag:z6X1VSmvQk4VV9GoOjidhA==,type:str]
    MAILER_EMAIL: ENC[AES256_GCM,data:/9ubYGHTgj44EDgsu3knQeuaVw==,iv:cd9L6UxYEB8MbeK/AkadAtim10y1LRlx9hwAFU5JTlk=,tag:j4iWZbvazLr7xkC2azzISA==,type:str]
    SMTP_HOST_ADDR: ENC[AES256_GCM,data:NHJE7fWbGSzlzJDN9iE=,iv:2ohrQ266TuwAu07YgwjuUwiBB+9WxuXkvXTeNrQfGSA=,tag:qS2ayjgfnNu9p+C6C4HYaw==,type:str]
    SMTP_HOST_PORT: ENC[AES256_GCM,data:GVp+,iv:7f3AtY1We6B9wym8t3Ro93+CF/9t8xrX18A3yruKACM=,tag:VojU527vUduWt88KDoZ+Kw==,type:str]
    SMTP_USER_NAME: ENC[AES256_GCM,data:/v6aoj9u8mZGX0cZiISfHSgsiQ==,iv:kYTPWZoTTpNTIRq4z9fRWNeuQKSvFP+QdPZIbGE0ISY=,tag:Z7LEGcr2BZVoNoLSYcclBg==,type:str]
    SMTP_USER_PWD: ENC[AES256_GCM,data:qmhBd2FUTw5XIYMair3e89bW/A==,iv:fWpR7NnPAeezTkenGIY/BXYqEyA1bnCX8J+ZKYb9f9k=,tag:y0LlBecW/MdXaMC/FnrKzQ==,type:str]
    CLICKHOUSE_DATABASE_URL: ENC[AES256_GCM,data:INjF2Z94xXMJS/2VXVQ0y7JtsZhC1DQG/AxaESq7i8HlJPP9u87IoOPtwiQ4/9Ff54k4kGs5rBWA2+vHnwhJCIHXliPUP5FYh0Ab72M0QaY8gzM5eNRrCjVTuUB6uBsNGoE=,iv:U+hcUECOOvGGzOicXBtHQ+Jh/e82sada8VqPVJhCqq0=,tag:nkXhVV87fFqBRxZImjtV3A==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVRcHZSUExIZ2syMDVo
            VlhFVDRvNXRwbloxbFFwRk5LdERhVTEvWERBCkZQUU40cjlHejg2TEtqUmtqS1NJ
            RFRIUVNYNHZwUWxVVUZjQW5WUGdsWG8KLS0tIFp3VHhrS0VNMllVRDFndW9BUkNM
            VklOcTJJdzQwYUVuOVhBajk3Q2UxV3cKmSDjqD402Ip0/Edsap5VGFSHuTCPqnbv
            6uRHHNZFoxI9ZY/JmP8WAjzNgXv5sLYYIIi+oSZT7a3NHISU/qIREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T19:23:31Z"
    mac: ENC[AES256_GCM,data:ge+21UozdErZhhmx7jsY/9Xs7Ky+2sfyiHNYzqRbw04tzbf/zaSa855jGOMXcuBMJFZCtP7t4XzPinr7beq1Fm1Ml8TDGnKXgl76sbU4VFd+smQx6eGqdoQxUCWudP3f1oRF3pxdundTkLqwgY9nL5IfNjW+7kCnAk+N5Yy/PRI=,iv:kGtOR88RPwclREP075wHyLiLesJ9pvosVvhN304P60w=,tag:J4GTZahqIzBJ49hUJu7Uuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
