apiVersion: v1
kind: Secret
metadata:
  name: mealie-secret
type: Opaque
stringData:
  POSTGRES_SERVER: ENC[AES256_GCM,data:nJgAdkgon9MHztYBJCydIim39u6NdvRE7R93BVCtmfxOBkXRXizHWLc=,iv:bI3MKa3rBuAfbOuDAOlgRUb7Rm80CWGa0gtbOEosra8=,tag:MH5haOAajk91jiqw5Hy4XA==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:ZPRTlA==,iv:websk54+GbAkdfcjDiOELrtlFSNTzUMaO4rm+SFf5f8=,tag:knVaTZ5r9sHn7TGCD0E1rw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:lxc27oSQ,iv:Q8pimkBphzt3o0OZSqkZwxOxsbdCtWf04TUNujKDKBU=,tag:wLIVdXKGvQaBMVo/XZb9Jg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:BrmEgMzASYg=,iv:ZAVrUhR/SksHTkPXIXxQjMyqcmuZ9mbLEhJ3/e5xObo=,tag:vw8+hull+NtxU9JPJJZOTw==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:sKdtEHFb,iv:7E/5EgA9GIC40uOPAPgmRXxViPngaXk0g3FlCSJD7YE=,tag:i6MaQbk/nnCoHOjOJ+3bYg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:6FXMYkOt,iv:fLB/lqNpE/iz8XW9zGgmxjitI8hs8U1Zw0mUmrJMc6o=,tag:UGZfFIeQHST1hZrTr8sO9g==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:izTj60m1DlKvqD5H6gh8v6zqrJ/5cSdMXCnvoZ94WpOx7g1qtBV0QJc=,iv:0bKPjo1l3rUgVcQ8vndEpFukgRTwYurzjF7l7UrbPxk=,tag:TFEAV9pj9BeNwsl2HUYutA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:TmZvVvWU,iv:c2k+871JNM0/RElAgBDncI98zFWnnz+d/KE3uQQZ6us=,tag:4l/4RfifayD/1t2BgNq+zg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:BeyWUyo7pAg=,iv:JvM/2DoI6/uRU3++/RWjXfhA+jMLUp5HSEyjXm24ihU=,tag:l/GexzyBSMd0d/ptW8sQxg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:PKqqAU1luSE=,iv:bkco6pt3kveazY8bhQ4L0iEMASYh4xaRA3HxC62wRtk=,tag:eHo7XlunYZs8FS1LS3tcTg==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQWhEWkVvLy9aU3Y2bXhR
        VlFRZDhIWGpQSlpPWWdwZ0NNUDRFejlZQldBCmp5dC9Jd3ROSGR1SjhmN2gva3h6
        aDRzMXMzeURsYVFJV2poSitxT01ZWFEKLS0tIDhuSVdNZlJ5TVdsTFhrVWorUGcr
        M0kxeEpCMzd0dlZucGp4WDlTeGN1am8KCmWkAhibHSMn5S+GYQ4hmC/+KUu4Y1Td
        YG+96hMzliOdVJ8atVZjV1LDGjjDa+O8CM6z0yeWx3hf/t4BoddkpQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T12:04:34Z"
  mac: ENC[AES256_GCM,data:aLpzAXiGmMIByipLEPTrFG10UFjitCCdwinjQzypT9yYz5J8Oy/tPJt1lXitIODN8gtT5cFzgvmaDF+i5YAcZ0eQvpQZouU5mUfQ4XonMoXBpx1z7D/KNhqifV7p5Bu8y8S6r3iAXiiyk6bOOlgBSUwVdLfacX3qaJ516SreJ5c=,iv:sZEdg8vCoLU//DlXWUsLQdZBVtDdz53TKMNYS9EYZNo=,tag:MPqIwwnh34pE91mngeuKGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
