apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:qBP4N1MviCsZzso=,iv:4+y8YCyDpaehKMRypYvNthnlIwH5uc4k6jL9Jz0ngXM=,tag:Ds0iE1P5b31R2DA+tIp+Cw==,type:comment]
  HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:gRV4HhJZGB12ysGVOpGnUbVqnoYKM5pT9qYzfKDvHt4=,iv:RX79OLpmulP4j3eIp5ne461e2YRzs+oJ89qfQnwscE8=,tag:e23NO/5DbRZzBDFBC60scQ==,type:str]
  HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:WyFAT7cITILQdYFmv0a+jzQel94mFXQEAlYt5swtYnE=,iv:OTymGYzIfDvdnrMblvcpeMI70PnzZG9m36gvkDE8yTE=,tag:2xdpO90M8jJ8cWh+RJTt9A==,type:str]
  HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:PFsPmZ+y9uuu1N0ArxTlD/z1q/+wcXMU4FbpyBZjrXw=,iv:uKTB60BIl2D/dxj/7lcQuPVnd4XLN3ddRDl9y0xzC0s=,tag:HyUx5JYMyzI2oIg3e59gtA==,type:str]
  HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:wONU5E1ppBYMwCJa7p5Xcpi9sLNa+4vGBX5qpabpNsU=,iv:PUk4Qy6sCU43IGHtdyw/NV68h1sNO4TuzA1A5pc4b48=,tag:FCa7Yz2eHKpenW8KiQqX9w==,type:str]
  HOMEPAGE_VAR_READARR_API_KEY: ENC[AES256_GCM,data:zUqrFuyWazA1EtDVAmc/H+U7xgm0UY8X/JU2+5eOxLE=,iv:ZweqK0dgd756f3Jv9lbkBBUtiSkx7707zc84Zk5OYtI=,tag:Za9VKKP/u8QHhtkp9nFDSw==,type:str]
  #ENC[AES256_GCM,data:GIFqcltIm6w5FA==,iv:KvvhGBDtPr7zhaJIQwi5tF2xYecgKpMWIcxZ3i14Mu4=,tag:BEL+NQ2gopV+1uQxeFw8UQ==,type:comment]
  HOMEPAGE_VAR_SABNZBD_API_KEY: ENC[AES256_GCM,data:JZEMAe2Ba8X1AEgp3g+q+fHgQXrzYG4S6yw4+byQMZU=,iv:a5mlsx6u+igfCGbPIgTlJwoNQQzuvDxdKi+0DmZl/us=,tag:xjDGXTMM2Y66T9+EoR7wIQ==,type:str]
  #ENC[AES256_GCM,data:eM3Ky2/Q,iv:GI35w5hFjsoSZW9PMUfp0K88WjtPgsGu7+j8bWU72xk=,tag:Bj+/vrUPM0ntoM6yXWbqTA==,type:comment]
  HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:WCKa7nZIPi9ED5YI0PILFHYM9kQ=,iv:MD1tfI9ha1NyebAiAi8Z2qPiTe38nnoumUhICAOPW/Y=,tag:OgOukMWELuqwp7pFOP8yzA==,type:str]
  HOMEPAGE_VAR_TAUTULLI_API_KEY: ENC[AES256_GCM,data:PGDeSxN7PpPqf0/Ek1O8xKc6VqGPbVGozAfLE7bVX/A=,iv:dXOqRqHr+f0ZwTfEQ/lupuLPQfXN5JUZY53RMvmw8Yo=,tag:Kh3IZ3wtxlbCIgzYb1Zqvw==,type:str]
  HOMEPAGE_VAR_OVERSEERR_API_KEY: ENC[AES256_GCM,data:ZtfHs6FEco+8FC0tZxZa+AAFfZyunyQpXybebh2aH0/oHQEFKKJhbLAG5Ckf5IPZ3B6Uxu+MaeW1nHQvWQy7rztYxbo=,iv:ZRKxYuKOnxihwq5whIAasW7zbmuNhk5tPpojkem5Lwo=,tag:enUH/lnOAGP+RPiwWndw+g==,type:str]
  #ENC[AES256_GCM,data:VDKtsH1cX02mTA==,iv:7x9VSridoRt1ngJ592faqXUc1gahPzi79hWpSdPIvTU=,tag:xI4L3D/2z7pbNlwKJw8Q0w==,type:comment]
  HOMEPAGE_VAR_PAPERLESS_API_KEY: ENC[AES256_GCM,data:cQ+i5skXHg6KrEHi8Yn+JY8w8WdGstKgFtAUzzwEdf2O1qud2lWXgg==,iv:gRRYUqrPf0UB/961IHxIHDiv59k1jN2oLZ50WYlqXXI=,tag:clthkHnIrGOv391jiJ6m4w==,type:str]
  HOMEPAGE_VAR_MEALIE_API_KEY: ENC[AES256_GCM,data:BiHZ2qwJx/Hjn7bWYqETwx6YTw9wcOtNE50YSR2nf1vtkCUJ,iv:ugPA4XfdvalEMRj6j+j3tsEDMJw02wyQpKSEnwNSoA0=,tag:j+ja0QHFVLpV8CRDm1oNYQ==,type:str]
  #ENC[AES256_GCM,data:tot5Y8qmmx6XLvgQECHD,iv:QgL9HM/+l/KZTxDg60mhtBxOCMz4Nc64kJtxTp21RXc=,tag:7Gtx2ni6MFnXj9NEKixGQA==,type:comment]
  HOMEPAGE_VAR_UNIFI_API_KEY: ENC[AES256_GCM,data:NoBtZLM6OLpt7xe20V6rcj2Nyggee5wnndWxL8O96bI=,iv:C/vBFFwCS3nfar2970vvP3FxzLlZYwDdzpdF1pNZ7Qg=,tag:s/H4hAE0YrjxqSmDZ+u09Q==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:hqPvkjE=,iv:5Jpn1Z24A4LkXbyKCxIo4Q0svvCdXT8rMEKHxWHlipE=,tag:bqV3N+jP4UEvMEwMXiPo1Q==,type:str]
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:MhQf/reWOtE3u3/D/IY=,iv:QwPYdm0BQVBXrLuyl0PuD5iFaSKNvw01/dVkFXVONAQ=,tag:fHjBPyi0A/EPBUa+ybo+3w==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:8WiFXwWmQLiy39z0hOnkzRA=,iv:Y8BvhjQUNp3NCbbBqUTqhIi78KlNBWU1M83jbbqsAsA=,tag:KabxzPxkbDK7cXyVIEEXmQ==,type:str]
  HOMEPAGE_VAR_PROXMOX_SECRET: ENC[AES256_GCM,data:uLZ0SBRwyrl8kGhyKY0lkghKnjeJhlLnlGHwT1n5HtaoCwX8,iv:5docvYJfUkiMSRDeQb+0+/6x6tCrV0fCZHpz4p2Va5k=,tag:QjVo3JSLEY0+x7eIE9atrQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVW5VRHBucURpR2lXeEtD
        WVFyRXl2c0F4ZUdCa1BUMS8rQjhkVk94UjI0CnNHbU03dC9mUGNrRkJKemw5MGMr
        NHlRcTNVUStXdW90a01aVHNIZFhHajAKLS0tIGpZbUZXWnptY2tuemxhcm9sclda
        K2NHZHNRTDBRMC9ZakNZRVRYTXl4YTQKnG3QFdY98wuBuidBEnXMy6Bpzsb0CosT
        QbTy73tffVwI9TTLifz27FLoDAdowQ7ut0Mkj/gsofPTUY1Kil61cQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T12:06:50Z"
  mac: ENC[AES256_GCM,data:JE/w0B/z8SO9sal3la24gQyib6X+7DDj62PkXk+z9E1SBrgv6LUkMRmWZHIxAxJX8R3vxQH6FNvPK515pSMs1pVC4kQCFgedkGpjBSz2XpPAUxSjIDGvNpq6PjD314kVU6ar6AGZYq2ya/xus81nTPeLZs/8dxiXixOgLt6922Q=,iv:PwxSjAVO9CPmdZGoXrqZMr+PDwYtUMQ4iW6joeVJtrA=,tag:owNwmZdol+E9N9cg4mJLIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
