apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Clkf5YqNHDgj/zc=,iv:XleLLDiCQRqJ1UIa/kZ0cW33PzN4qT4g1qtIYs5IXNU=,tag:jZflGV82piMA7mctnBkivA==,type:comment]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:FpNwdJ1oFre8hrw6UVvLJsIrQle15MQqb3BZeClPE3I=,iv:pMQsAqTe9wg/zteKifNLjfMp1xraZ11sbRQt/59U5Qw=,tag:W2wdcnydvPnbUzc+F8mK3A==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:XmzrIx9hWZJ8Q9Fxa25lSPhcbYt1Y+fTtVscnxktyL8=,iv:2RVNpgFY8dVOjohRC0kAwBMzyrDgCR8/JiVjBOfSfwo=,tag:p4owp33q9zxXOrrPHQl68Q==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:+BIVpY8RgHhvVg3Xm05l6CThXH9ABI7ewbl9zFotK/w=,iv:P8+zE71RtXHuBBIUxmhs4CuScWonyottb3tjksL48Kg=,tag:7i2nKp0rQIKLh1uWcNrMtg==,type:str]
    HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:yOl9LFzceARlBiG1DAF1J5iwszY6+QkgtbKK+OpVvb0=,iv:RbsobH85dBgW6gcC17a469chBidhhdG4yFnZNp8hr00=,tag:BktMRvUtjiNNuWcsdFVUZA==,type:str]
    #ENC[AES256_GCM,data:explk+053UFeYg==,iv:8S+Ugzvcec+SKKX5G3DFuXXxePDSbbrwJvk14X0xbr8=,tag:jXIIGzik07xZjrdMxf+bEg==,type:comment]
    HOMEPAGE_VAR_SABNZBD_API_KEY: ENC[AES256_GCM,data:lzsd5nWQoNyba60FLxM8HV9OpwyStndk5W2jEbIEg4I=,iv:Mkjdsar6uAdh+oUAfzqYt2Qn3h7sjR7oev2iZRLP41I=,tag:KD2ACnnUDhEOXfg9KZEmjQ==,type:str]
    #ENC[AES256_GCM,data:5AzZwTco,iv:BXPd7HTbkMisBhyyYT/080G6S4NlzgQsvb/hxQIRltk=,tag:RI2gWTdLklO4xxA+Ty1FCQ==,type:comment]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:VjFSg+vI4X0eHhW/YWGN7XsVp2I=,iv:xOWRJI1qloJ3Vug6N5mogrkCnNQfz7xu05SggKouyEo=,tag:ixnzfBgi6NyDBY+b+99g7Q==,type:str]
    HOMEPAGE_VAR_TAUTULLI_API_KEY: ENC[AES256_GCM,data:D29877gEVkaOV8mvtwTiw/7UwJXDezostYayRwpcXaM=,iv:bb8TFm+7ONJpRCrTfIXq6VPC4tKgPkYhFS5tM9WiRcU=,tag:dWLT5no2FfHbcl9fr+h34g==,type:str]
    #ENC[AES256_GCM,data:x9XN2HbDgIg//di64/Xy,iv:7kvU2Gg830o3XDUITlB5LgSg0zZF428gQ45mzdg0ug4=,tag:Y7wcWZWCgHuduVQcyvnvFA==,type:comment]
    HOMEPAGE_VAR_UNIFI_API_KEY: ENC[AES256_GCM,data:5qpeJigyyFlAcRqVxID4eH9gk3RX0xYSHn045/OP0ks=,iv:fK3jCQYnxLB6sMSVQoPvUEwlSdlP4ucSx8ngie5Yiz0=,tag:jE5FxA3cE9vd304DS6oaEg==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:P8mUauY=,iv:vyZWV51Z/C1T8bWLr+L4KPlsS6GqLO5kc60pbkAZWNE=,tag:l+RYl+N/NSZW2h3zLQntmA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:BNNYo762BGWjHbEY6R0=,iv:CE0tKW5FQ8ad3HiSfPH2p9lcr/8YzJNKt+SeAXFMmz4=,tag:rr/0pzOSKaCYePZLBszhKg==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:Ui9wjXC3hx4=,iv:WFyZGoofj4HIKbGwfif2OQI9cwCXkxK9bzWOiLs/9YY=,tag:67Q8DhO4I63vCkpl1Yfekw==,type:str]
    HOMEPAGE_VAR_PROXMOX_SECRET: ENC[AES256_GCM,data:TY50HgAwOuYZ7787if0=,iv:Er2SAKF31zuCA+oyUa39rPMEoX4aorYxYunSBLYCsqY=,tag:WLvIEhjqD0RRs1/xVbnDtQ==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZktnUnFVdkkyVThhclpS
            UHVWbGdWZFFOWkNtbFBabDBwRTRFRGJGd2trCnFqcW95TGRHSUUyZ2daZ2VFL1ZH
            Q0NYc242TW5WKzJkNjhzMjkxWEgzb00KLS0tIDNzSXJqd05UdlM1VTYyU1pSczJK
            L0RJMzVIc2ZJQ0JuR0V3RXdyWkhrSU0Ktn3ojOwxlpXIZvgI0EfaWeNlje6kczJ4
            1VSsEYAezWylrTeoTK7Pf865NxFJbM2RvojqBNzC77hjVYgD9V9k3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T17:56:08Z"
    mac: ENC[AES256_GCM,data:jEN4o+teXhue5uSG+uYD1ODg99JO3AWD8+Z3N22znL/9AE6tg7X4XfR4BAbbZFKHCAmk1n27XWvzVoZdO6CkDnQbApwHPlyXmkQv9tNfZszQk31aZGhVbNUWPKrWtI6HMvCOeu2zNrHp1wIIJQD14OytHVnYJiNiYZdINk4CLHo=,iv:NB4LWlpwllxLriJO4msjPvhU1Z2r5pHNsPwz7IfyVPI=,tag:lnibs9E00dPl4s+7y0AF+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
