apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:o+DK60DpfsKVhdk=,iv:CZGjJB4cthKBrOgctjDITQJNu9YWNKTdKIMhzhCLBzI=,tag:o3B7buKfNOHEGHLMvvh63Q==,type:comment]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:v6ir32LSVVOOxJ4XbWjWneJJUlLYAXOoV3+3Fr9Gzhc=,iv:JgS5nTdH3zocHkdOLlpXkgMFsDvioF1DolkR2BHzaIc=,tag:kIencrMNzkd2PpgioHDrPw==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:8qpO28hapiQNIa+Em8MmHs9HTVRpyWPYgaJxvllIK3s=,iv:m6XznJBbNFdtAPouG9oje8j1qejADExviAhYL5YG5kg=,tag:N14RpspYap+ya3sSbA9J4w==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:WZIazcuBrxMRCAesPoWfp3YBbf4E0l6jK+agCxBMWto=,iv:URgMFIVrvjyyA4adzNHCyP0ehLCaJTgJwDYpcNlyx5s=,tag:uFXUYpCDWWKE6vxI3Q2N1A==,type:str]
    HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:ag7sYkP9kztdQkhDSKzqUj7sUmk6B7bwxCt24QgzlLU=,iv:QUjHC99jUIKDKYzMC8ZcrwOX3zZqgEE6tsYo1KMaMZw=,tag:dpq58uHcLTfl1kMpNrhTJA==,type:str]
    #ENC[AES256_GCM,data:Vb/zUboTWbSEeg==,iv:hjAf5MPo2L2FB2NzNtpbDons+BAsDjx3ONO7QolUPRg=,tag:tOvRkTMJ0bW/4F8Ez3evtg==,type:comment]
    HOMEPAGE_VAR_SABNZBD_API_KEY: ENC[AES256_GCM,data:QBmTM13uGEoUte9f9DJFeS5Zr93d47sXbRZXHsyzVaQ=,iv:o7Cp8+epHdPZmn/guWp7rfzXDPzAAiBXu07m5LM43xY=,tag:PQb8I0fAHwF8GNuQp3pI7A==,type:str]
    #ENC[AES256_GCM,data:j7qr6Rgr,iv:ADQ2Fv3Is6hx5PvjDhlGyDMSURh/brnTSZ9+DbxKZFo=,tag:pRv3cfoVEKvcmM+RQBj+Lg==,type:comment]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:I3a9gxdsDnutuc/oquBBHIZb/JE=,iv:0ZgYhK3TNs+/Zd8Uq+bEnolgfsHfyocsND3xG5w3Pls=,tag:rITMctK774QN/qM1GgXaIg==,type:str]
    HOMEPAGE_VAR_TAUTULLI_API_KEY: ENC[AES256_GCM,data:Q+QACAcYl9YhB/UOnuMQknO8jB1AwL5eyntJ0Xsx4jo=,iv:dQUjNxEkmh3lgbilsbpW8YvODCecwI0frZlPEvidv2s=,tag:bQYAOFy19yGogR+gTeoZuQ==,type:str]
    #ENC[AES256_GCM,data:XHDOcgSI6ex1jcUvzdzg,iv:3DrLafItjoXVMNloeYIpC5jSyYuDTczeCO3E2vfxHKc=,tag:CTGRaHx42GcmUlBaF9S6JQ==,type:comment]
    HOMEPAGE_VAR_UNIFI_API_KEY: ENC[AES256_GCM,data:oOWNsuAMo1QZL0a3bgML2r8ek+iWBt6uFF6QkEvECRE=,iv:FNgd13KCsD6QgTjE/nSNFPbpKAcfZYYlw6TZeO7QoAo=,tag:yWhWVaH9xbUYYBASR+5PqQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:o2Fb2pQ=,iv:woYrMOlY9BuML0Z6w5hO4FHQ2eCbnMXQjf82erVgbB8=,tag:9+OMhrwjISYgWoQlkMRQsQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:lH9mYYOQu6/SJCrxAAk=,iv:p2Bo2WEFeqPktpqFKhGRMzyIataps1XpfGZP7bDAMQM=,tag:1/m2hRk7Kf90PMAs+Cgd0w==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:iuATqVpOqLvUrmFG6t42o50=,iv:oABTDdIc+fKR8OnaSL1NDsu/Cmo1C5E/0otiF+wFEmc=,tag:L769NMP45krjiS4neelbdw==,type:str]
    HOMEPAGE_VAR_PROXMOX_SECRET: ENC[AES256_GCM,data:frt4Mewjqoo724KECordyow8Jz141nhHeVvdmStUYXVJqNPG,iv:5nAhJq/XsXLZlBVoOFHpl/8UuQMeO26KL4MGuSxHDNM=,tag:tIQlp1IZeAQIvLnj9YWPxA==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMGowdEI1ekFCTkdUQ1lU
            OXg3NnlSaDl0Ym93S29LQmI2b293elQwbkhzCkdiUFB4cmhIL1MwZXRUcmxSbFBK
            QTR0dnEySFVMeHp6YmZlYTFMYTZ5L2MKLS0tIEQvSGZkWjduczN1UDJMK0U0YURE
            TzlkR0hrMitaaElMVWJjQjJaNm9NQkEKm3fZFiHPR3joJxp2cc43LH3nCqzb9MRr
            3WKlapN5jf3C0wgMVNWyrtDSafqdd8DcEitag3ScO5kfChLHUMcLNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T18:12:44Z"
    mac: ENC[AES256_GCM,data:4B7tabN2rgAAlxnDg2+bIrDPPR1rFP/pTGHJBi/Ql9+opvrZWp2eyVYa+L/b3fbLMzEHRKC3KxwgE22wIRDPpvlzyg+52Ms/XryHersWz54B9crF9iHjwD01SPn9tmJm5jSFGRs0GrbeXtF2kaje9W9nk/964WRv62KMB8CnHUk=,iv:BkDmSw8X/aUULnfesm3/yxiule3YjputfGqrxtMWh84=,tag:b3Jy8x481dxa+JzdBYwmwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
