apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:xrW34cF2nkPD6fY=,iv:hfaEfFzWf2QHXg+AYFsy9amplnaghptowTZtW8m99aI=,tag:4G4hTYMG/LEZmm23Bdeh6Q==,type:comment]
  HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:fYup+qrAkcdFrDunpRw0asd93Zy5O02oEGtNgn4ArfE=,iv:XxjO58SkJMSnq5GMzkEmfCYl6CBi4jYbV5UjM4yF6Bw=,tag:kc8eLOl/FTmCZdAFnOvalw==,type:str]
  HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:1p4E/cXm2lMtHLnYL5w6gYXN5TheVwgmjfBha3BGZB0=,iv:dq5nP/3RCQerL1YLlpHC8kjgtw7cYxTyRnBT77EbR/g=,tag:v8/pZUyuNX7wachJ+s/IYg==,type:str]
  HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:fZtpr/LqzkjZM+jAV8rKnptZFM7ENxmkNg0cmVzSGNI=,iv:1Wb6U5W/pHR1ihxi/jVxP9bbYHBl0uPH9JUhmv5Njw0=,tag:JVV/w73GLGLk7eOEb3gWvg==,type:str]
  HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:ryMrMVCegPRLaGKTB2snO0D8k9kTEV7NJu2EdK2g9N0=,iv:3pnYTmeu34BN0VXLKcg5NqYpDieDWmQru62UT2hGAL4=,tag:8nf23LtyTYzey1/3JoP/qQ==,type:str]
  #ENC[AES256_GCM,data:lJbcCwLc1LK37w==,iv:CvBlytlWHp3UuLHm59MvzOrldH9JD4/Iu0ewfAl7lhM=,tag:u1i7X2RiPquWPut7lESo3w==,type:comment]
  HOMEPAGE_VAR_SABNZBD_API_KEY: ENC[AES256_GCM,data:voHCsAESZCGd5hqssiu03kN8tLSlTykiUFi0+dmKlNg=,iv:0eaz41k1woR6fRiEeRofn1l9hCzbtvJXOjNZb69iNko=,tag:86HKVzyccGXX8xI0EXIrEw==,type:str]
  #ENC[AES256_GCM,data:BQr3zpdC,iv:h5naQOyl6Gj/i0JrgdENm6YqpOCiUfIm21/OtBvSaiM=,tag:ZPplYgZPz1dQZyDospnFOQ==,type:comment]
  HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:M1OCoVdixYqFYMbKof0yrQbKh8c=,iv:m9cdBqwNgJx5qpsBFW9p0lKFM1hD0oJ89zUdLsUDPpI=,tag:TRW6k7HC5Pwx6HH05GZkWQ==,type:str]
  HOMEPAGE_VAR_TAUTULLI_API_KEY: ENC[AES256_GCM,data:ClvaB0665uj3ZX3+KwSDvcagmHse5ORVLaN2vmOHl1w=,iv:BnRuYpMVKDLMUQkuokV8T1Ey1C4Xyp6/fyN7YELy9ig=,tag:p1UnG3EdMx5p2FIQlPl9qA==,type:str]
  HOMEPAGE_VAR_OVERSEERR_API_KEY: ENC[AES256_GCM,data:gfmPiefw/ODEtgUMfA8q+50zX8bAC9w6tfHCv7SrZsAapdstlEYhrvIQRAbgKeXvnTqI+I3ql/A9IrtdYyah/0jhGms=,iv:jYbC5+HGN99ubTY/9DFmpbNyyNMNdcH7xMI3ioKaYwE=,tag:Y9BWqyV65Zx9dfeO/chVFA==,type:str]
  #ENC[AES256_GCM,data:MVLFhLEvYo0rv6LE0Ke1,iv:B1CdMEVqEmrBJxehiUko2QZGn/1To3npQRsRhcU58m8=,tag:x/37yvxvT3mSkbiEA/fMbg==,type:comment]
  HOMEPAGE_VAR_UNIFI_API_KEY: ENC[AES256_GCM,data:8C8el98SK1DyBUSNYl1hOiIsPnBkl6uhvMI4u5xQmYM=,iv:OZaWjP0V7INwWN5gNwFXUmjKXJyv4wI/k4hA/jyvKFg=,tag:/ul9oqTtMLtpjcEQZ9pgvA==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:E3Jome0=,iv:RhfRZ3shtPp0wcHRxmgocYhgJ3hQWDDEKRG7+1TrJzY=,tag:leKMYuR3PjKx9Tw6G9YItg==,type:str]
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Wgvn4fMc9bh/+tvm2yQ=,iv:Y66fIBL1+M5nXdHVd3ns7cgcoKRO6wnp5do8BnL2jcs=,tag:ktbZ2XWL8BtPbxPSicniUg==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:IyHVhYbxvsDzXl9DiECQ608=,iv:5ouKCRjwtX9PmXOKpmasehQrM3swzhJJppcnSyaEn5U=,tag:xujHgxwzcP1+ScQNxx59tw==,type:str]
  HOMEPAGE_VAR_PROXMOX_SECRET: ENC[AES256_GCM,data:s/GlTf92g7cI+jzHWP/irno3qUeqejVCs7ViASUPpbXuH4o7,iv:BLO87/E46IvA1vwd4F1oIt906wqIc1npTCWyJa5MId4=,tag:ICqps8tgJUzDMIJ1uz4nJQ==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkLzQrRmRsUXBtdlI0cXBG
        azhPQ1pteHdGdTV0Q3FDZlBHQkR5dWtCOWtNCmEvWHl4dHY2N1hkR0trdi9XVjIw
        K1ZabzRKNk85alVRNUNxbTVRblZvWVUKLS0tIDhDOW5zR1pQQmhhd25UVGpXMTlK
        OXozUUl6dUxoQk9jTitkdjMxMzFjaUEKCE1whuOs5nFBjHXlok0JzbS4nAJPO79t
        vNHZkK36kRStZLU9X0mbC7u8cRPicYD/uGgZQ9UzdzVn43TjUwmYZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T11:23:55Z"
  mac: ENC[AES256_GCM,data:J5HbscZUxFjd4VZgBtlx3K6uxNNQNu4KR77cQ5LAsAEtGVgF2hqjkKwSJWEe6BGSFaE8W5oz5Gk/o4Po+AgI+pzmj4dLbzZ0pPiD8t/+qhnaLewaZ0qpPbyUG/JC5Byk9KyD0DNkwb+O/CB9OaIaSrfraVs1J9wPmjzWTC2h0bA=,iv:vck5Jn6SvG4y+/lJFUkY0/SOUcoMqvDcjJ/ePKoQyKU=,tag:DEMmAnZ2Imi4sQV3fqYwTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
