apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:cEk811gLx88CVJfHd8/BVu5SKX9nW5GOGEEMIkkMokg=,iv:zL8YjH3B5zlOvv8asy7RSWEHgfo/HDW83YZU53xq4cE=,tag:csn2McNYkkFBfPCtIFJ4BA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:r+oFQdQf6f/91u1xMTVkK6YUdPskEr2GP/0gA55ATFw=,iv:yNDSBKfTCjStJ75p3sMXKK3n33hqA4PlSAEMUM41TmE=,tag:06v93//GcV95ons9yFpZOg==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:2RhD/sWCsllSMbPpSl3TXDbplolkpKOKyayVOaYAf/I=,iv:PCBqbKwd5GSi3xBhWqS2d+rHnQ+YTEsEmGI23QD3wx0=,tag:aQQ6n8/ndv2tIjxIKF5AdQ==,type:str]
    UNIFI_API_KEY: ENC[AES256_GCM,data:J2PcElA5Jpf98Epm6QibW2dh2p23BeCF6EQA1F7Z53g=,iv:KirrL12ZvNpV9fDV1ffL3wpSVJBhcL000ooAoUYVfyo=,tag:ws3el6A5lngbO0LbqPsCOw==,type:str]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:TzYGgB4=,iv:UytN0SrzXavedl8ya0+lwjCGO8/idlFh+N6IVyCRcO0=,tag:LkD4Bnu91Q5INFyvvV+rpQ==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:sSXkNhC7WjGItkSRsDQ=,iv:cvnrBIRZYWVs7FPcOzo6Iwte7Tw8EvwSQYeS6cScLTM=,tag:Bp152XTf7yrUvab5zIAHqQ==,type:str]
    PROXMOX_TOKEN: ENC[AES256_GCM,data:JfBMEqqvLAU=,iv:cdRVK01ra0jG7/geXDUp8dWaOChLKp7WU5eKGKpMyO8=,tag:/UxIGeYKM4bmaXFUwD6VHA==,type:str]
    PROXMOX_SECRET: ENC[AES256_GCM,data:mTcX1i6pGXny2vZP08c=,iv:NGDqNXFCmNhwAroBOC+JHrURNCOrNsqE9W5aGDGdhWE=,tag:4KeZsOUzjqviiaJxJF2hmg==,type:str]
sops:
    age:
        - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTk0zU1VJRnpFR3JHQUhm
            amx0UytWc2t5WUZHclptUC9pZzlaTGRiMkNZCkxhM1dCdjMzUVJ4UjdJZlQ5TG9r
            ckZ6RVA0WG9EVGlXUVpiZnlVMXVXa1kKLS0tIGlLVFFZZnhzTUtES1l0ZkNnaC9B
            MnFFZVMxSkJzWVhUVzI0VzcrUWdEMGcK/2waxNybcJEtKDKfuH4AhGqT4faoW6uh
            g8rVm2NLzmNhl/g9qIY7VtgiKxBbL/USWdWAe7abuWZWXkLre06cGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T17:26:30Z"
    mac: ENC[AES256_GCM,data:tB/+9eIwEtw1/ZPaYR2SMbkjrzsvNR47OSxc56+FXaETzuQNZG38jQbAFJJGs+VJRU4q810NxXv5ACbVQ9jXopo/qOKrX566g5AExFX5KX+5IyE9OjttscfN7vtVv068HddyYyQpCYLsMzclRg1yKlQ5tSJaTr+Jln3wPOV/siw=,iv:laJWqkvFx2OnGCF6l1OWE0O8udIoDwGGYDM8lA0BC2Y=,tag:tPHYvrUjnZZbWnqDtpzB4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
