---
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"

- proxmox:
    proxmoxNode: nucleus
    fields:
      - vms
      - lxc
      - resources.cpu
      - resources.mem

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false

- openmeteo:
    label: Bucharest
    latitude: 44.4268
    longitude: 26.1025
    timezone: Europe/Bucharest
    units: metric
