apiVersion: v1
kind: Secret
metadata:
  name: paperless-gpt-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:ohU9fB0Fv9rilGzExVN8eJFwaodeZoFJeXU8Q6UrkEUPT0ZBfqPb1CwP6KNVjWivhcb+hENGGowPep7EcHr11e1UINw=,iv:A2Ym8VJ7DZII5ZwX16w9VpWAVBNwL5K5r5gt/wsMPEU=,tag:QtwsJ4viiq2Q4rNpacXt3g==,type:comment]
  PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:kpgJCbdFJfzuyaM/FGTVF39wbgMMmTJyJnGb5GJTTZ8CoEIMqx/Wdw==,iv:Ene8QueDwhmU0ehkfDSKnWD56DGdX0YsV0AcY5CInJs=,tag:dORuC+QpTP4lWe7zwEy2Sg==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSVMyVHV2UTgxdmdZRlNZ
        bEgvRTVzaTdXQ0thNDRIa2ovaERtT01JL0VZCjRqRTBJZnhLb3l0UTdHTXU5blFW
        Ync2MFoxY2FJcTNHR1FZc0pCVk1ES0UKLS0tIHc2dlFUdW5pUUFoL1p3Vmg0Sldx
        TStlZjZqalM0Qkh0R1A2TDdGbThUbVEK4GBzoEJtZbrWZs4pHnjSKX5qXMyiDZGo
        E7UjbQ9wk5OCnOl3HjQ5y57ctXEVcqHl0T3FjL0xGRKx2DmsA3RSzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T00:00:45Z"
  mac: ENC[AES256_GCM,data:1IQAGjeejyWWl9PvgFLnw4Z6qBrbPQLwe7TC42scAKEjcwwXtxc4Me1thQ7BPajtsEZ76MgvUdEeWPWks11vlCrFfmUuELQAucecK5mADJ/1f/rTw8O1XxP+vL4mIXmWPq6sunY05wJflFw80MchE843NvU4ItUa41rXRCWx5iM=,iv:TbTD+Qo/07+IoxkzGUB+uB/ZanzTWkjDPd7+qPBVYJ8=,tag:qspxYSplwcjTm7urdf5wFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
