apiVersion: v1
kind: Secret
metadata:
  name: volsync-secret
type: Opaque
stringData:
  VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:wuNTSnDEhgDJHLlPii0T,iv:R14fABmY5u+ZxoXdf+8B9MMDIMEYjZigz9WKUQeo/TE=,tag:sFEe6cOz/YIbN6zoBUUGrw==,type:str]
  VOLSYNC_S3_ACCESS_KEY: ENC[AES256_GCM,data:tZbQq7I=,iv:lXUJeeAG5FqgGgzGFDHtGfKqw00iFZQ1fhsYrawVcfU=,tag:8e1VK0I84gbT/mvqsGEjiw==,type:str]
  VOLSYNC_S3_SECRET_KEY: ENC[AES256_GCM,data:rFtGXHrpYJr1YXte98U=,iv:grpWUFc5nkB6l563aFzmZ+9rh01dlk63/+iQreqkSUY=,tag:Xw+4iuEhuxpTQ/IymjjIng==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzelN6eUtuUWZBNVN4OEo5
        NXFFdG9WaDJqV3g2YnlIK0hyVk5HbWdaZW5VCm5uWnVRS1BUY2JaWXFwbFU1VmdQ
        eHM5aFVEWG8xblVDdG1qUzNZWnhPS2sKLS0tIGdua3VlWm1qdzc2cG8wRE43OXNk
        VXEvMlRWWk1ZRDRWMzhpY0JNTWI4YzQKLlXezTMlZ8iccVwsBnbxGhwY13p/fZvV
        pNGYiPCmSwszBzd2iWpo1nhrUr2yJ1e5iSSXPp59INhfLPzAF/Cd5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T17:09:46Z"
  mac: ENC[AES256_GCM,data:eBhO3bu2LfK3GQP0CM1xy/7IUGVEtSBmhu1H7Cco+c1jmAcq87TDu1K/N7c0LWimdlngcsEhatRdhx+ArGdAif7aQs2IN9S47fVApie3z9llqVNbu2tDJwrDxHNB7AO+Uxfo4+mVcVKRo4SYsDmCsFA35Ro1m2dMsfLUEeccghM=,iv:oL3E9PsE0+6qEJ2xe93vBQdoEFjophdU+RDRvKvrpR4=,tag:vckx8ZUaLojGhcUHyzK3Og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
