apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-secret
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:gjdbMR+KjhgG1RYIFOPY0HIodN1pC7QnHL8Tqz0NHLTMUBKwQzXblvLEELu6Kfq3qE2yXImnHLM3z4/EniTQAhGz9McK+3gA1CH9S9OgLcCLU7WtJ+gBRAJ0,iv:rtcf46c/RDW4bDW8y2i3Hjru21fgKqL3FGZZE0cI2Sw=,tag:3XMPNKifcnCvhlh2w3oF9Q==,type:str]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:TadHIMqTCuTv8S4uXdW7qB6FvlrMyl6OL9rQsYk48/hsFKtS,iv:F7/5svuHPOlieaUJiBZpWpBYGCQjLkOdBXOGVX6My0U=,tag:tUdtPTDmszzWrvYLyI587g==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:9U7K7sVz6B8oWQ==,iv:TMR7K+78mEbICnjPTGnpeMJqguWegNmsiigYi0FqOfE=,tag:EJejxDD5XdTogEkSNf74bA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:XLQuSZy5DUTN1u3jW7PMM8mutCCKfdfhrCh2814qRBg+Xgq0llnv1gE=,iv:43l+U8vEtSCP3+Ty1lfx1OuBbnfdXC6LsgC4zr7Eqk8=,tag:aWYTjZhhGbDt0FmDUVmmuw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:WIOX4pcWduqGYA==,iv:Rur6i818pbJ0/BEYg8lonR+jwgCwEt7fNrC0xBbOGn4=,tag:M7syoO7/l72Pyuyccqvtmg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Q4on+uzU1Ws=,iv:akf3+Z25ztjjei4vnETBSAYSHzZ+qBENOpsLC57KZ74=,tag:/BbooNCtG+angdeKpRgp1Q==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:GKPAWW3KvBXyJ2AzYF0=,iv:ctkjjuJFtToV5dlnGLv+VVPyvGcmhoYIg4tsUXo7QAI=,tag:0YlqDytmwIexW1mpdsE28g==,type:str]
sops:
  age:
    - recipient: age1y7qev2y6htku2fv659svnevvk6d42luh2cexk03u2veje5vasy4smv4mc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOWxOd0ZoY2xwSS84ckg4
        aGJyZHpHcklEeEdpL2V3UzU5S2hmS2FwcmhvCk9CUUUrN0EwL3NIOUxBR2hCaUlt
        Z2cwcjlOSXhhem85d0pxMGtDTHZZTDQKLS0tIFZrTlhMYVY1OU5LM25VVWlxWUdy
        VitSS2RVUTZ6b0NSS3MvUm9qLy8ydTAKFCx6+2oo2WBtl7uBjoIgul4P6lqKxJBU
        Swek+OXRxwBbcZFdeHfykO0LHwYl3Cxpwv63CXakhuTssKAahJF3Sw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T11:38:55Z"
  mac: ENC[AES256_GCM,data:PhTCFuqkJSz8L4NObgJQGO5AXfmBS4PaQwjrCG+ypbXQVTdYWFGGLTP9pqh9y403veJz2N0xt3OBKBaq00i2221LlTwzQPYlZQaKPAjAwED91xIzmOWTCCVoOHdad7VcBf7ZdYmsix1Nda9yCuow3u+sXUmdyER3ckupEtCqGp8=,iv:M+m+XHsbwka00I5mSerqNHd3dFjG342ofs9zSbJ79IU=,tag:9xdwBat18Iu/KlRnN9I89g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
